### ISSUE TITLE
issue on installing module

### ISSUE THREAD

**Issue by eynavbe** [E0HYL/MsDroid#4]
We are conducting research on your classifier. We install andrgurd 3.4 and pyg as required but while running
Training script we have this error.
Any suggestions to solve this?

~/Downloads/MsDroid-main/src$ python train.py -i /home/einav/Downloads/niv_avi_files
Traceback (most recent call last):
  File "/home/einav/Downloads/MsDroid-main/src/train.py", line 17, in <module>
    from training import set_train_config, GraphDroid
  File "/home/einav/Downloads/MsDroid-main/src/training/__init__.py", line 14, in <module>
    from .train_and_test import set_train_config, GraphDroid
  File "/home/einav/Downloads/MsDroid-main/src/training/train_and_test.py", line 16, in <module>
    from torch_geometric.data import DataLoader
  File "/home/einav/anaconda3/lib/python3.9/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/einav/anaconda3/lib/python3.9/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/einav/anaconda3/lib/python3.9/site-packages/torch_geometric/data/data.py", line 9, in <module>
    from torch_sparse import SparseTensor
  File "/home/einav/anaconda3/lib/python3.9/site-packages/torch_sparse/__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/einav/anaconda3/lib/python3.9/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/home/einav/anaconda3/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libc10_cuda.so: cannot open shared object file: No such file or directory

**Comment by max190113** [comment]
There are different versions of Pytorch. for cuda, You need something else to do beforehand.
Make good use of search engines
